# docker-compose file version
version: '3'

# app services
services:
  # database service
  db:
    # custom image with setup database
    image: mysql:8.0
    # container name
    env_file:
      - ./.env
    container_name: todoapp_db
    # restart app always except when manually stoppped
    restart: unless-stopped
    # allow connection with native password
    command: --default-authentication-plugin=mysql_native_password
    # port mapping
    ports:
      - 3306:3306
    # environment variables
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: todoapp
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./db:/var/lib/mysql"

  frontend:
      container_name: frontend
      build:
        context: ./front
        dockerfile: Dockerfile

      # Set environment variables directly in the docker-compose file
      environment:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

      # Set envrionment variables based on the .env file
      env_file:
        - .env
      volumes:
        - ./front/src:/app/src
        - ./front/public:/app/public
      restart: always
      ports:
        - 3000:3000

  backend:
      build:
        context: ./back
        dockerfile: Dockerfile
      container_name: backend
      environment:
        - PORT=${PORT}
      ports:
        - '8000:8000'
      depends_on:
        - db
      volumes:
        - ./back/src:/app/src